version: '3'

networks:
    nginx-php81-mysql8-node:

services:

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - nginx-php81-mysql8-node

    # php
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/project
        networks:
            - nginx-php81-mysql8-node

    mysql:
        image: mysql:8
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_DATABASE: demo_crypto_exchange
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_ROOT_HOST: localhost
        networks:
            - nginx-php81-mysql8-node

    # node
    node-service:
        image: node:latest
        container_name: node
        volumes:
            - .:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php81-mysql8-node