version: "3"

services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www/symfony:cached
        ports:
            - "80:80"

    php:
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/symfony:cached

    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"

volumes:
    mysql:
