controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login-check

app_catch_all:
    path: /{path}
    controller: App\Controller\EntryController::index
    requirements:
        path: .*